const $=id=>document.getElementById(id);
const E={viewport:$("viewport"),language:$("language"),newBtn:$("new"),save:$("save"),png:$("png"),
top:$("top"),home:$("home"),wallHint:$("wallHint"),mode:$("mode"),empty:$("empty"),content:$("content"),
close:$("close"),oname:$("oname"),otype:$("otype"),px:$("px"),py:$("py"),pz:$("pz"),sx:$("sx"),sy:$("sy"),sz:$("sz"),
wallprops:$("wallprops"),length:$("length"),thick:$("thick"),mat:$("mat"),del:$("del"),cx:$("cx"),cy:$("cy"),cz:$("cz")};
import * as THREE from "three";import{OrbitControls}from"three/addons/controls/OrbitControls.js";
const v=E.viewport,s=new THREE.Scene();s.background=new THREE.Color(0x0c1014);const c=new THREE.PerspectiveCamera(45,1,.1,500);c.position.set(12,10,14);const r=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.shadowMap.enabled=true;r.outputColorSpace=THREE.SRGBColorSpace;v.appendChild(r.domElement);const ctl=new OrbitControls(c,r.domElement);ctl.enableDamping=true;ctl.target.set(0,1,0);s.add(new THREE.HemisphereLight(0xc5d3df,0x20252c,2));let sun=new THREE.DirectionalLight(0xffffff,2.6);sun.position.set(7,14,8);sun.castShadow=true;s.add(sun);s.add(new THREE.GridHelper(40,80,0x4b5662,0x252c34));let floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({color:0x11161b,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-.01;floor.receiveShadow=true;s.add(floor);
const objs=[];let selected=null,tool="select",start=null,temp=null,n=1;const ray=new THREE.Raycaster(),ptr=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
function box(name,type,p,z,col){let m=new THREE.Mesh(new THREE.BoxGeometry(z.x,z.y,z.z),new THREE.MeshStandardMaterial({color:col,roughness:.65}));m.name=name;m.position.set(p.x,p.y,p.z);m.castShadow=m.receiveShadow=true;m.userData={type,size:{...z},material:"Concrete"};s.add(m);objs.push(m);return m}
box("Main Volume","Building",{x:0,y:1.5,z:0},{x:8,y:3,z:6},0x7e8994);box("Upper Volume","Building",{x:.8,y:3.7,z:-.2},{x:5.4,y:1.4,z:4.2},0x9aa3ad);
function point(e){let q=r.domElement.getBoundingClientRect();ptr.x=(e.clientX-q.left)/q.width*2-1;ptr.y=-(e.clientY-q.top)/q.height*2+1;ray.setFromCamera(ptr,c);let p=new THREE.Vector3();return ray.ray.intersectPlane(plane,p)?new THREE.Vector3(Math.round(p.x*2)/2,0,Math.round(p.z*2)/2):null}
function wall(a,b){let dx=b.x-a.x,dz=b.z-a.z,L=Math.hypot(dx,dz);if(L<.25)return;let m=new THREE.Mesh(new THREE.BoxGeometry(L,3,.2),new THREE.MeshStandardMaterial({color:0x8f9aa6,roughness:.7}));m.position.set((a.x+b.x)/2,1.5,(a.z+b.z)/2);m.rotation.y=-Math.atan2(dz,dx);m.name="Wall "+n++;m.castShadow=m.receiveShadow=true;m.userData={type:"Wall",size:{x:L,y:3,z:.2},material:"Concrete",thickness:.2};s.add(m);objs.push(m);select(m)}
function select(o){if(selected)selected.material.emissive.set(0);selected=o;if(o)o.material.emissive.set(0x202020);update()}
function update(){E.empty.hidden=!!selected;E.content.hidden=!selected;if(!selected)return;E.oname.textContent=selected.name;E.otype.textContent=selected.userData.type;E.px.value=selected.position.x.toFixed(2);E.py.value=selected.position.y.toFixed(2);E.pz.value=selected.position.z.toFixed(2);E.sx.value=selected.userData.size.x.toFixed(2);E.sy.value=selected.userData.size.y.toFixed(2);E.sz.value=selected.userData.size.z.toFixed(2);E.wallprops.hidden=selected.userData.type!=="Wall";if(selected.userData.type==="Wall"){E.length.textContent=selected.userData.size.x.toFixed(2)+" m";E.thick.value=selected.userData.thickness}}
r.domElement.onpointerdown=e=>{if(tool==="wall"){let p=point(e);if(!p)return;if(!start){start=p;temp=new THREE.Mesh(new THREE.BoxGeometry(.01,.06,.06),new THREE.MeshBasicMaterial({color:0x77d995}));s.add(temp)}else{if(temp)s.remove(temp);wall(start,p);start=null;document.querySelector('[data-tool="wall"]').classList.remove("wallactive");document.querySelector('[data-tool="wall"]').classList.add("active");tool="select";E.wallHint.classList.remove("show")}return}if(tool!=="select")return;let q=r.domElement.getBoundingClientRect();ptr.x=(e.clientX-q.left)/q.width*2-1;ptr.y=-(e.clientY-q.top)/q.height*2+1;ray.setFromCamera(ptr,c);let hits=ray.intersectObjects(objs);select(hits[0]?.object||null)};
r.domElement.onpointermove=e=>{if(tool==="wall"&&start&&temp){let p=point(e);if(p){let L=Math.hypot(p.x-start.x,p.z-start.z);temp.scale.x=L;temp.position.set((p.x+start.x)/2,.03,(p.z+start.z)/2);temp.rotation.y=-Math.atan2(p.z-start.z,p.x-start.x)}}};
document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tool").forEach(x=>x.classList.remove("active","wallactive"));b.classList.add(b.dataset.tool==="wall"?"wallactive":"active");tool=b.dataset.tool;if(tool==="wall")E.wallHint.classList.add("show");else{E.wallHint.classList.remove("show");start=null;if(temp){s.remove(temp);temp=null}}});
document.onkeydown=e=>{if(e.key==="Escape"){start=null;if(temp)s.remove(temp);temp=null;E.wallHint.classList.remove("show");tool="select";document.querySelectorAll(".tool").forEach(x=>x.classList.remove("wallactive"));document.querySelector('[data-tool="select"]').classList.add("active")}};
E.close.onclick=()=>select(null);E.del.onclick=()=>{if(selected){s.remove(selected);objs.splice(objs.indexOf(selected),1);select(null)}};E.home.onclick=()=>{c.position.set(12,10,14);ctl.target.set(0,1,0)};E.top.onclick=()=>{c.position.set(0,25,.01);ctl.target.set(0,0,0)};E.newBtn.onclick=()=>location.reload();E.save.onclick=()=>{let b=new Blob([JSON.stringify(objs.map(o=>({name:o.name,type:o.userData.type,position:o.position.toArray(),size:o.userData.size,material:o.userData.material})),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="archiforge-project.json";a.click()};E.png.onclick=()=>{let a=document.createElement("a");a.href=r.domElement.toDataURL("image/png");a.download="archiforge-view.png";a.click()};
function resize(){r.setSize(v.clientWidth,v.clientHeight,false);c.aspect=v.clientWidth/v.clientHeight;c.updateProjectionMatrix()}addEventListener("resize",resize);resize();function loop(){requestAnimationFrame(loop);ctl.update();r.render(s,c)}update();loop();